// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzCK9i5WsdJRIn7vbM1L9GMX161UC5Opk',
    appId: '1:545973513291:web:5079319e5f73894a8871ce',
    messagingSenderId: '545973513291',
    projectId: 'testlogintest',
    authDomain: 'testlogintest.firebaseapp.com',
    storageBucket: 'testlogintest.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZ4-P1A7PWIzEgmdeieTOqSo3naSc0EQ',
    appId: '1:545973513291:android:ff850669a95b6db38871ce',
    messagingSenderId: '545973513291',
    projectId: 'testlogintest',
    storageBucket: 'testlogintest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5SnqsG5ein4P-Z5GZP6z4pvgdiwCKwwE',
    appId: '1:545973513291:ios:b365bc7f7037ebe38871ce',
    messagingSenderId: '545973513291',
    projectId: 'testlogintest',
    storageBucket: 'testlogintest.appspot.com',
    iosBundleId: 'com.example.logintest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5SnqsG5ein4P-Z5GZP6z4pvgdiwCKwwE',
    appId: '1:545973513291:ios:b365bc7f7037ebe38871ce',
    messagingSenderId: '545973513291',
    projectId: 'testlogintest',
    storageBucket: 'testlogintest.appspot.com',
    iosBundleId: 'com.example.logintest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzCK9i5WsdJRIn7vbM1L9GMX161UC5Opk',
    appId: '1:545973513291:web:6e90af489363eb068871ce',
    messagingSenderId: '545973513291',
    projectId: 'testlogintest',
    authDomain: 'testlogintest.firebaseapp.com',
    storageBucket: 'testlogintest.appspot.com',
  );

}